image: "python:3.7"

before_script:
  - python --version
  - conda env create --prefix ./envs --file environment.yml
  - conda activate ./envs

stages:
  - Static Analysis
  - Test
  - Documentation

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint --disable=no-member Hyperparameter_Optimization

unit_test:
  stage: Test
  script:
  - python ./Hyperparameter_Optimization/test_Running_HO_on_CNN.py
  
doc:
  stage: Documentation
  script:
  - pdoc --html --html-dir ./doc/ --overwrite ./Hyperparameter_Optimization/Running_HO_on_CNN_doc.py
